package com.example.video.videoapp.data.db.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTENTS".
*/
public class ContentsDao extends AbstractDao<Contents, Long> {

    public static final String TABLENAME = "CONTENTS";

    /**
     * Properties of entity Contents.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property YoutubeID = new Property(1, Long.class, "youtubeID", false, "youtubeID");
        public final static Property PlayID = new Property(2, Long.class, "playID", false, "playID");
        public final static Property Title = new Property(3, Long.class, "title", false, "title");
    }

    private DaoSession daoSession;


    public ContentsDao(DaoConfig config) {
        super(config);
    }
    
    public ContentsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"youtubeID\" INTEGER," + // 1: youtubeID
                "\"playID\" INTEGER," + // 2: playID
                "\"title\" INTEGER);"); // 3: title
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTENTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Contents entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long youtubeID = entity.getYoutubeID();
        if (youtubeID != null) {
            stmt.bindLong(2, youtubeID);
        }
 
        Long playID = entity.getPlayID();
        if (playID != null) {
            stmt.bindLong(3, playID);
        }
 
        Long title = entity.getTitle();
        if (title != null) {
            stmt.bindLong(4, title);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Contents entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long youtubeID = entity.getYoutubeID();
        if (youtubeID != null) {
            stmt.bindLong(2, youtubeID);
        }
 
        Long playID = entity.getPlayID();
        if (playID != null) {
            stmt.bindLong(3, playID);
        }
 
        Long title = entity.getTitle();
        if (title != null) {
            stmt.bindLong(4, title);
        }
    }

    @Override
    protected final void attachEntity(Contents entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Contents readEntity(Cursor cursor, int offset) {
        Contents entity = new Contents( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // youtubeID
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // playID
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // title
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Contents entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setYoutubeID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setPlayID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Contents entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Contents entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Contents entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getImagesDao().getAllColumns());
            builder.append(" FROM CONTENTS T");
            builder.append(" LEFT JOIN IMAGES T0 ON T.\"_id\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Contents loadCurrentDeep(Cursor cursor, boolean lock) {
        Contents entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Images images = loadCurrentOther(daoSession.getImagesDao(), cursor, offset);
        entity.setImages(images);

        return entity;    
    }

    public Contents loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Contents> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Contents> list = new ArrayList<Contents>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Contents> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Contents> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
